openapi: 3.0.3
info:
  title: Content service
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: image
    description: Everything about your Pets

paths:
  /v1/images:
    post:
      tags:
        - image
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Images"

  /v1/image/{image_id}:
    get:
      tags:
        - image
      parameters:
        - in: path
          name: image_id
          required: true
          schema:
            type: integer
      summary: Получение фотографии по id
      operationId: GetImage
      responses:
        "200":
          description: OK
          content:
            image/png:
              schema:
                type: string
                format: binary
        "403":
          description: Forbiden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - image
      parameters:
        - in: path
          name: image_id
          required: true
          schema:
            type: integer
      summary: Удаление фотографии по id
      operationId: DeleteImage
      responses:
        "200":
          description: OK
          content:
            text/plain
components:
  schemas:
    Images:
      type: array
      items:
        type: object
        required:
          - image_id
        properties:
          image_id:
            type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
  parameters:
    image_id:
      in: path
      name: image_id
      required: true
      schema:
        type: integer
